debug: false
server:
  port: 8081
  tomcat:
    uri-encoding: utf-8
spring:
  application:
    name: 开发环境
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:MySQL://localhost:3306/sys?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    names: secondary
    secondary:
        driver-class-name: org.sqlite.JDBC
        url: jdbc:sqlite:./data/smartapp.db
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  security:
    user:
      name: admin
      password: nimda
      roles: admin
logging:
  level:
    root: info
    org:
     springframework:
      web: info
      boot: info

